targetScope = 'subscription'

@description('Name of the resource group created for this independent demo deployment.')
param resourceGroupName string = 'rg-aurelia-agency-ai-repro'

@description('Azure region for App Service, Foundry, and model deployments.')
param location string = 'swedencentral'

@description('Lowercase prefix used to derive globally unique resource names.')
@minLength(3)
@maxLength(32)
param baseName string = 'aurelia-agency-ai'

@description('Username included in the salted portal credential hash.')
@minLength(1)
param portalUsername string

@secure()
@description('Salted scrypt hash generated by scripts/provision-azure.ps1. Never pass plaintext credentials.')
param portalCredentialHash string

@secure()
@minLength(32)
@description('Random secret used to sign the eight-hour portal session cookie.')
param portalSessionSecret string

@description('Deploy MAI-Image-2.5. Disable only when image-model quota is unavailable.')
param deployMai bool = true

@description('GPT deployment model version.')
param gptModelVersion string = '2026-07-09'

@description('GPT GlobalStandard capacity in thousands of tokens per minute.')
@minValue(1)
param gptCapacity int = 10

@description('MAI deployment model version.')
param maiModelVersion string = '2026-06-02'

@description('MAI GlobalStandard capacity.')
@minValue(1)
param maiCapacity int = 1

@description('Tags applied to all resources.')
param tags object = {
  application: 'Aurelia Agency AI Studio'
  environment: 'demo'
  managedBy: 'Bicep'
}

var uniqueSuffix = uniqueString(subscription().subscriptionId, resourceGroupName)
var appName = take('${toLower(baseName)}-${uniqueSuffix}', 60)
var appServicePlanName = take('${toLower(baseName)}-${uniqueSuffix}-plan', 40)
var aiAccountName = take('${toLower(baseName)}-${uniqueSuffix}', 64)

resource resourceGroup 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: resourceGroupName
  location: location
  tags: tags
}

module resources './resources.bicep' = {
  name: 'aurelia-agency-resources'
  scope: resourceGroup
  params: {
    location: location
    appName: appName
    appServicePlanName: appServicePlanName
    aiAccountName: aiAccountName
    portalCredentialHash: portalCredentialHash
    portalSessionSecret: portalSessionSecret
    deployMai: deployMai
    gptModelVersion: gptModelVersion
    gptCapacity: gptCapacity
    maiModelVersion: maiModelVersion
    maiCapacity: maiCapacity
    tags: tags
  }
}

output resourceGroupName string = resourceGroup.name
output appName string = resources.outputs.appName
output appUrl string = resources.outputs.appUrl
output aiAccountName string = resources.outputs.aiAccountName
output portalUsername string = portalUsername
output gptDeployment string = resources.outputs.gptDeployment
output maiDeployment string = resources.outputs.maiDeployment
